version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: mydb
      DB_USERNAME: root
      DB_PASSWORD: example
    ports:
      - "5173:5173"
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - tools_bullken
    depends_on:
      - db

  webserver:
    image: nginx:latest
    ports:
      - "1001:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - tools_bullken

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
    networks:
      - tools_bullken

networks:
  tools_bullken:
    driver: bridge