name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no root@194.233.91.59 "cd websites/tools.bullken.click.www && git pull origin master && docker exec -w /var/www/tools.bullken.click toolsbullkenclickwww-app-1 composer install && docker exec -w /var/www/tools.bullken.click toolsbullkenclickwww-app-1 npm run build"
